version: "3.7"

services:
    database: 
        image: postgres
        container_name: fin_api
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpass
            - POSTGRES_DB=fin_api
        volumes: 
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local